/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AgentAccountMinimalInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "balance"
      | "execute"
      | "isTargetAllowed"
      | "owner"
      | "policy"
      | "setDailyLimit"
      | "setTargetAllowed"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DailyLimitSet"
      | "Deposit"
      | "Executed"
      | "TargetAllowed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "balance", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isTargetAllowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "policy", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setDailyLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTargetAllowed",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "balance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTargetAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "policy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTargetAllowed",
    data: BytesLike
  ): Result;
}

export namespace DailyLimitSetEvent {
  export type InputTuple = [owner: AddressLike, limitWei: BigNumberish];
  export type OutputTuple = [owner: string, limitWei: bigint];
  export interface OutputObject {
    owner: string;
    limitWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutedEvent {
  export type InputTuple = [
    owner: AddressLike,
    target: AddressLike,
    value: BigNumberish,
    spentToday: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    target: string,
    value: bigint,
    spentToday: bigint
  ];
  export interface OutputObject {
    owner: string;
    target: string;
    value: bigint;
    spentToday: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TargetAllowedEvent {
  export type InputTuple = [
    owner: AddressLike,
    target: AddressLike,
    allowed: boolean
  ];
  export type OutputTuple = [owner: string, target: string, allowed: boolean];
  export interface OutputObject {
    owner: string;
    target: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentAccountMinimal extends BaseContract {
  connect(runner?: ContractRunner | null): AgentAccountMinimal;
  waitForDeployment(): Promise<this>;

  interface: AgentAccountMinimalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  balance: TypedContractMethod<[], [bigint], "view">;

  execute: TypedContractMethod<
    [target: AddressLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;

  isTargetAllowed: TypedContractMethod<
    [target: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  policy: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        dailyLimitWei: bigint;
        currentDay: bigint;
        spentToday: bigint;
      }
    ],
    "view"
  >;

  setDailyLimit: TypedContractMethod<
    [limitWei: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTargetAllowed: TypedContractMethod<
    [target: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "balance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [target: AddressLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isTargetAllowed"
  ): TypedContractMethod<[target: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policy"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        dailyLimitWei: bigint;
        currentDay: bigint;
        spentToday: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setDailyLimit"
  ): TypedContractMethod<[limitWei: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTargetAllowed"
  ): TypedContractMethod<
    [target: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DailyLimitSet"
  ): TypedContractEvent<
    DailyLimitSetEvent.InputTuple,
    DailyLimitSetEvent.OutputTuple,
    DailyLimitSetEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "Executed"
  ): TypedContractEvent<
    ExecutedEvent.InputTuple,
    ExecutedEvent.OutputTuple,
    ExecutedEvent.OutputObject
  >;
  getEvent(
    key: "TargetAllowed"
  ): TypedContractEvent<
    TargetAllowedEvent.InputTuple,
    TargetAllowedEvent.OutputTuple,
    TargetAllowedEvent.OutputObject
  >;

  filters: {
    "DailyLimitSet(address,uint256)": TypedContractEvent<
      DailyLimitSetEvent.InputTuple,
      DailyLimitSetEvent.OutputTuple,
      DailyLimitSetEvent.OutputObject
    >;
    DailyLimitSet: TypedContractEvent<
      DailyLimitSetEvent.InputTuple,
      DailyLimitSetEvent.OutputTuple,
      DailyLimitSetEvent.OutputObject
    >;

    "Deposit(address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "Executed(address,address,uint256,uint256)": TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;
    Executed: TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;

    "TargetAllowed(address,address,bool)": TypedContractEvent<
      TargetAllowedEvent.InputTuple,
      TargetAllowedEvent.OutputTuple,
      TargetAllowedEvent.OutputObject
    >;
    TargetAllowed: TypedContractEvent<
      TargetAllowedEvent.InputTuple,
      TargetAllowedEvent.OutputTuple,
      TargetAllowedEvent.OutputObject
    >;
  };
}
