/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CertIssuerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ISSUER_COUNT"
      | "MAX_VALIDITY"
      | "QUORUM"
      | "anchorLeafCounts"
      | "anchorRoot"
      | "anchorRoots"
      | "attestations"
      | "isIssuer"
      | "isValid"
      | "issueAttestation"
      | "issuerSet"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AttestationIssued" | "RootAnchored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ISSUER_COUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_VALIDITY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "QUORUM", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "anchorLeafCounts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "anchorRoot",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "anchorRoots",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "attestations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "issueAttestation",
    values: [BigNumberish, BigNumberish, BytesLike, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "issuerSet",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ISSUER_COUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_VALIDITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "QUORUM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "anchorLeafCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "anchorRoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "anchorRoots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isIssuer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isValid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issueAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "issuerSet", data: BytesLike): Result;
}

export namespace AttestationIssuedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    certType: BigNumberish,
    capabilitiesHash: BytesLike,
    issuedAt: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    certType: bigint,
    capabilitiesHash: string,
    issuedAt: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    certType: bigint;
    capabilitiesHash: string;
    issuedAt: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RootAnchoredEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    root: BytesLike,
    leafCount: BigNumberish
  ];
  export type OutputTuple = [agentId: bigint, root: string, leafCount: bigint];
  export interface OutputObject {
    agentId: bigint;
    root: string;
    leafCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CertIssuer extends BaseContract {
  connect(runner?: ContractRunner | null): CertIssuer;
  waitForDeployment(): Promise<this>;

  interface: CertIssuerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ISSUER_COUNT: TypedContractMethod<[], [bigint], "view">;

  MAX_VALIDITY: TypedContractMethod<[], [bigint], "view">;

  QUORUM: TypedContractMethod<[], [bigint], "view">;

  anchorLeafCounts: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  anchorRoot: TypedContractMethod<
    [agentId: BigNumberish, root: BytesLike, leafCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  anchorRoots: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  attestations: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint] & {
        certType: bigint;
        capabilitiesHash: string;
        issuedAt: bigint;
        expiresAt: bigint;
      }
    ],
    "view"
  >;

  isIssuer: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isValid: TypedContractMethod<[agentId: BigNumberish], [boolean], "view">;

  issueAttestation: TypedContractMethod<
    [
      agentId: BigNumberish,
      certType: BigNumberish,
      capabilitiesHash: BytesLike,
      expiresAt: BigNumberish,
      sigs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  issuerSet: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ISSUER_COUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_VALIDITY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "QUORUM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "anchorLeafCounts"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "anchorRoot"
  ): TypedContractMethod<
    [agentId: BigNumberish, root: BytesLike, leafCount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "anchorRoots"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "attestations"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint] & {
        certType: bigint;
        capabilitiesHash: string;
        issuedAt: bigint;
        expiresAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isIssuer"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValid"
  ): TypedContractMethod<[agentId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "issueAttestation"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      certType: BigNumberish,
      capabilitiesHash: BytesLike,
      expiresAt: BigNumberish,
      sigs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "issuerSet"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "AttestationIssued"
  ): TypedContractEvent<
    AttestationIssuedEvent.InputTuple,
    AttestationIssuedEvent.OutputTuple,
    AttestationIssuedEvent.OutputObject
  >;
  getEvent(
    key: "RootAnchored"
  ): TypedContractEvent<
    RootAnchoredEvent.InputTuple,
    RootAnchoredEvent.OutputTuple,
    RootAnchoredEvent.OutputObject
  >;

  filters: {
    "AttestationIssued(uint256,uint8,bytes32,uint64,uint64)": TypedContractEvent<
      AttestationIssuedEvent.InputTuple,
      AttestationIssuedEvent.OutputTuple,
      AttestationIssuedEvent.OutputObject
    >;
    AttestationIssued: TypedContractEvent<
      AttestationIssuedEvent.InputTuple,
      AttestationIssuedEvent.OutputTuple,
      AttestationIssuedEvent.OutputObject
    >;

    "RootAnchored(uint256,bytes32,uint256)": TypedContractEvent<
      RootAnchoredEvent.InputTuple,
      RootAnchoredEvent.OutputTuple,
      RootAnchoredEvent.OutputObject
    >;
    RootAnchored: TypedContractEvent<
      RootAnchoredEvent.InputTuple,
      RootAnchoredEvent.OutputTuple,
      RootAnchoredEvent.OutputObject
    >;
  };
}
