/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace InterchangeSettlement {
  export type SettlementStruct = {
    gatewayId: string;
    day: string;
    tier: BigNumberish;
    volumeWei: BigNumberish;
    gatewayBps: BigNumberish;
    agentidBps: BigNumberish;
    gatewayAmountWei: BigNumberish;
    agentidAmountWei: BigNumberish;
  };

  export type SettlementStructOutput = [
    gatewayId: string,
    day: string,
    tier: bigint,
    volumeWei: bigint,
    gatewayBps: bigint,
    agentidBps: bigint,
    gatewayAmountWei: bigint,
    agentidAmountWei: bigint
  ] & {
    gatewayId: string;
    day: string;
    tier: bigint;
    volumeWei: bigint;
    gatewayBps: bigint;
    agentidBps: bigint;
    gatewayAmountWei: bigint;
    agentidAmountWei: bigint;
  };

  export type DaySettlementStruct = {
    batchRoot: BytesLike;
    totalVolumeWei: BigNumberish;
    gatewayCount: BigNumberish;
    settledAt: BigNumberish;
  };

  export type DaySettlementStructOutput = [
    batchRoot: string,
    totalVolumeWei: bigint,
    gatewayCount: bigint,
    settledAt: bigint
  ] & {
    batchRoot: string;
    totalVolumeWei: bigint;
    gatewayCount: bigint;
    settledAt: bigint;
  };
}

export interface InterchangeSettlementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CONFIG_DELAY"
      | "MAX_GATEWAY_BPS"
      | "MIN_GATEWAY_BPS"
      | "UPGRADE_INTERFACE_VERSION"
      | "agentidBpsForVolume"
      | "agentidCredit"
      | "applyAgentidBps"
      | "applyTreasury"
      | "claim"
      | "claimed"
      | "dailySettlements"
      | "deriveSplit"
      | "getDaySettlement"
      | "initialize"
      | "isClaimed"
      | "maxAgentidBps"
      | "minAgentidBps"
      | "operators"
      | "owner"
      | "pendingMaxAgentidBps"
      | "pendingMinAgentidBps"
      | "pendingTreasury"
      | "proxiableUUID"
      | "renounceOwnership"
      | "scheduleAgentidBps"
      | "scheduleTreasury"
      | "setOperator"
      | "settleDay"
      | "settlementLeaf"
      | "transferOwnership"
      | "treasury"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentidBpsChangeScheduled"
      | "AgentidBpsChanged"
      | "DaySettled"
      | "Initialized"
      | "OperatorSet"
      | "OwnershipTransferred"
      | "SettlementClaimed"
      | "TreasuryChangeScheduled"
      | "TreasuryChanged"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CONFIG_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_GATEWAY_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_GATEWAY_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentidBpsForVolume",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agentidCredit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "applyAgentidBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "applyTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [
      BigNumberish,
      InterchangeSettlement.SettlementStruct,
      BytesLike[],
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "claimed",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dailySettlements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deriveSplit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDaySettlement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isClaimed",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxAgentidBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minAgentidBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "operators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingMaxAgentidBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingMinAgentidBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleAgentidBps",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "settleDay",
    values: [BigNumberish, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settlementLeaf",
    values: [InterchangeSettlement.SettlementStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "CONFIG_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_GATEWAY_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_GATEWAY_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentidBpsForVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentidCredit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyAgentidBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dailySettlements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deriveSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDaySettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isClaimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxAgentidBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minAgentidBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operators", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingMaxAgentidBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingMinAgentidBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleAgentidBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settleDay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settlementLeaf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace AgentidBpsChangeScheduledEvent {
  export type InputTuple = [
    newMin: BigNumberish,
    newMax: BigNumberish,
    executableAfter: BigNumberish
  ];
  export type OutputTuple = [
    newMin: bigint,
    newMax: bigint,
    executableAfter: bigint
  ];
  export interface OutputObject {
    newMin: bigint;
    newMax: bigint;
    executableAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentidBpsChangedEvent {
  export type InputTuple = [newMin: BigNumberish, newMax: BigNumberish];
  export type OutputTuple = [newMin: bigint, newMax: bigint];
  export interface OutputObject {
    newMin: bigint;
    newMax: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DaySettledEvent {
  export type InputTuple = [
    day: BigNumberish,
    batchRoot: BytesLike,
    totalVolumeWei: BigNumberish,
    gatewayCount: BigNumberish
  ];
  export type OutputTuple = [
    day: bigint,
    batchRoot: string,
    totalVolumeWei: bigint,
    gatewayCount: bigint
  ];
  export interface OutputObject {
    day: bigint;
    batchRoot: string;
    totalVolumeWei: bigint;
    gatewayCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorSetEvent {
  export type InputTuple = [operator: AddressLike, allowed: boolean];
  export type OutputTuple = [operator: string, allowed: boolean];
  export interface OutputObject {
    operator: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementClaimedEvent {
  export type InputTuple = [
    day: BigNumberish,
    leafHash: BytesLike,
    gatewayId: string,
    payee: AddressLike,
    gatewayAmountWei: BigNumberish,
    agentidAmountWei: BigNumberish
  ];
  export type OutputTuple = [
    day: bigint,
    leafHash: string,
    gatewayId: string,
    payee: string,
    gatewayAmountWei: bigint,
    agentidAmountWei: bigint
  ];
  export interface OutputObject {
    day: bigint;
    leafHash: string;
    gatewayId: string;
    payee: string;
    gatewayAmountWei: bigint;
    agentidAmountWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryChangeScheduledEvent {
  export type InputTuple = [
    newTreasury: AddressLike,
    executableAfter: BigNumberish
  ];
  export type OutputTuple = [newTreasury: string, executableAfter: bigint];
  export interface OutputObject {
    newTreasury: string;
    executableAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryChangedEvent {
  export type InputTuple = [newTreasury: AddressLike];
  export type OutputTuple = [newTreasury: string];
  export interface OutputObject {
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InterchangeSettlement extends BaseContract {
  connect(runner?: ContractRunner | null): InterchangeSettlement;
  waitForDeployment(): Promise<this>;

  interface: InterchangeSettlementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CONFIG_DELAY: TypedContractMethod<[], [bigint], "view">;

  MAX_GATEWAY_BPS: TypedContractMethod<[], [bigint], "view">;

  MIN_GATEWAY_BPS: TypedContractMethod<[], [bigint], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  agentidBpsForVolume: TypedContractMethod<
    [volumeWei: BigNumberish],
    [bigint],
    "view"
  >;

  agentidCredit: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  applyAgentidBps: TypedContractMethod<[], [void], "nonpayable">;

  applyTreasury: TypedContractMethod<[], [void], "nonpayable">;

  claim: TypedContractMethod<
    [
      day: BigNumberish,
      s: InterchangeSettlement.SettlementStruct,
      proof: BytesLike[],
      payee: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  claimed: TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;

  dailySettlements: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        batchRoot: string;
        totalVolumeWei: bigint;
        gatewayCount: bigint;
        settledAt: bigint;
      }
    ],
    "view"
  >;

  deriveSplit: TypedContractMethod<
    [tier: BigNumberish, volumeWei: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        gatewayBps: bigint;
        agentidBps: bigint;
        gatewayAmountWei: bigint;
        agentidAmountWei: bigint;
      }
    ],
    "view"
  >;

  getDaySettlement: TypedContractMethod<
    [day: BigNumberish],
    [InterchangeSettlement.DaySettlementStructOutput],
    "view"
  >;

  initialize: TypedContractMethod<
    [owner_: AddressLike, treasury_: AddressLike],
    [void],
    "nonpayable"
  >;

  isClaimed: TypedContractMethod<
    [day: BigNumberish, leafHash: BytesLike],
    [boolean],
    "view"
  >;

  maxAgentidBps: TypedContractMethod<[], [bigint], "view">;

  minAgentidBps: TypedContractMethod<[], [bigint], "view">;

  operators: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingMaxAgentidBps: TypedContractMethod<
    [],
    [[bigint, bigint] & { value: bigint; executableAfter: bigint }],
    "view"
  >;

  pendingMinAgentidBps: TypedContractMethod<
    [],
    [[bigint, bigint] & { value: bigint; executableAfter: bigint }],
    "view"
  >;

  pendingTreasury: TypedContractMethod<
    [],
    [[string, bigint] & { value: string; executableAfter: bigint }],
    "view"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  scheduleAgentidBps: TypedContractMethod<
    [newMin: BigNumberish, newMax: BigNumberish],
    [void],
    "nonpayable"
  >;

  scheduleTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  setOperator: TypedContractMethod<
    [operator: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  settleDay: TypedContractMethod<
    [
      day: BigNumberish,
      batchRoot: BytesLike,
      totalVolumeWei: BigNumberish,
      gatewayCount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  settlementLeaf: TypedContractMethod<
    [s: InterchangeSettlement.SettlementStruct],
    [string],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CONFIG_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_GATEWAY_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_GATEWAY_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agentidBpsForVolume"
  ): TypedContractMethod<[volumeWei: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentidCredit"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "applyAgentidBps"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "applyTreasury"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [
      day: BigNumberish,
      s: InterchangeSettlement.SettlementStruct,
      proof: BytesLike[],
      payee: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "dailySettlements"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        batchRoot: string;
        totalVolumeWei: bigint;
        gatewayCount: bigint;
        settledAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deriveSplit"
  ): TypedContractMethod<
    [tier: BigNumberish, volumeWei: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        gatewayBps: bigint;
        agentidBps: bigint;
        gatewayAmountWei: bigint;
        agentidAmountWei: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDaySettlement"
  ): TypedContractMethod<
    [day: BigNumberish],
    [InterchangeSettlement.DaySettlementStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [owner_: AddressLike, treasury_: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isClaimed"
  ): TypedContractMethod<
    [day: BigNumberish, leafHash: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxAgentidBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minAgentidBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "operators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingMaxAgentidBps"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { value: bigint; executableAfter: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingMinAgentidBps"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { value: bigint; executableAfter: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingTreasury"
  ): TypedContractMethod<
    [],
    [[string, bigint] & { value: string; executableAfter: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scheduleAgentidBps"
  ): TypedContractMethod<
    [newMin: BigNumberish, newMax: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scheduleTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<
    [operator: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleDay"
  ): TypedContractMethod<
    [
      day: BigNumberish,
      batchRoot: BytesLike,
      totalVolumeWei: BigNumberish,
      gatewayCount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settlementLeaf"
  ): TypedContractMethod<
    [s: InterchangeSettlement.SettlementStruct],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "AgentidBpsChangeScheduled"
  ): TypedContractEvent<
    AgentidBpsChangeScheduledEvent.InputTuple,
    AgentidBpsChangeScheduledEvent.OutputTuple,
    AgentidBpsChangeScheduledEvent.OutputObject
  >;
  getEvent(
    key: "AgentidBpsChanged"
  ): TypedContractEvent<
    AgentidBpsChangedEvent.InputTuple,
    AgentidBpsChangedEvent.OutputTuple,
    AgentidBpsChangedEvent.OutputObject
  >;
  getEvent(
    key: "DaySettled"
  ): TypedContractEvent<
    DaySettledEvent.InputTuple,
    DaySettledEvent.OutputTuple,
    DaySettledEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorSet"
  ): TypedContractEvent<
    OperatorSetEvent.InputTuple,
    OperatorSetEvent.OutputTuple,
    OperatorSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SettlementClaimed"
  ): TypedContractEvent<
    SettlementClaimedEvent.InputTuple,
    SettlementClaimedEvent.OutputTuple,
    SettlementClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryChangeScheduled"
  ): TypedContractEvent<
    TreasuryChangeScheduledEvent.InputTuple,
    TreasuryChangeScheduledEvent.OutputTuple,
    TreasuryChangeScheduledEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryChanged"
  ): TypedContractEvent<
    TreasuryChangedEvent.InputTuple,
    TreasuryChangedEvent.OutputTuple,
    TreasuryChangedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AgentidBpsChangeScheduled(uint16,uint16,uint64)": TypedContractEvent<
      AgentidBpsChangeScheduledEvent.InputTuple,
      AgentidBpsChangeScheduledEvent.OutputTuple,
      AgentidBpsChangeScheduledEvent.OutputObject
    >;
    AgentidBpsChangeScheduled: TypedContractEvent<
      AgentidBpsChangeScheduledEvent.InputTuple,
      AgentidBpsChangeScheduledEvent.OutputTuple,
      AgentidBpsChangeScheduledEvent.OutputObject
    >;

    "AgentidBpsChanged(uint16,uint16)": TypedContractEvent<
      AgentidBpsChangedEvent.InputTuple,
      AgentidBpsChangedEvent.OutputTuple,
      AgentidBpsChangedEvent.OutputObject
    >;
    AgentidBpsChanged: TypedContractEvent<
      AgentidBpsChangedEvent.InputTuple,
      AgentidBpsChangedEvent.OutputTuple,
      AgentidBpsChangedEvent.OutputObject
    >;

    "DaySettled(uint256,bytes32,uint256,uint256)": TypedContractEvent<
      DaySettledEvent.InputTuple,
      DaySettledEvent.OutputTuple,
      DaySettledEvent.OutputObject
    >;
    DaySettled: TypedContractEvent<
      DaySettledEvent.InputTuple,
      DaySettledEvent.OutputTuple,
      DaySettledEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OperatorSet(address,bool)": TypedContractEvent<
      OperatorSetEvent.InputTuple,
      OperatorSetEvent.OutputTuple,
      OperatorSetEvent.OutputObject
    >;
    OperatorSet: TypedContractEvent<
      OperatorSetEvent.InputTuple,
      OperatorSetEvent.OutputTuple,
      OperatorSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SettlementClaimed(uint256,bytes32,string,address,uint256,uint256)": TypedContractEvent<
      SettlementClaimedEvent.InputTuple,
      SettlementClaimedEvent.OutputTuple,
      SettlementClaimedEvent.OutputObject
    >;
    SettlementClaimed: TypedContractEvent<
      SettlementClaimedEvent.InputTuple,
      SettlementClaimedEvent.OutputTuple,
      SettlementClaimedEvent.OutputObject
    >;

    "TreasuryChangeScheduled(address,uint64)": TypedContractEvent<
      TreasuryChangeScheduledEvent.InputTuple,
      TreasuryChangeScheduledEvent.OutputTuple,
      TreasuryChangeScheduledEvent.OutputObject
    >;
    TreasuryChangeScheduled: TypedContractEvent<
      TreasuryChangeScheduledEvent.InputTuple,
      TreasuryChangeScheduledEvent.OutputTuple,
      TreasuryChangeScheduledEvent.OutputObject
    >;

    "TreasuryChanged(address)": TypedContractEvent<
      TreasuryChangedEvent.InputTuple,
      TreasuryChangedEvent.OutputTuple,
      TreasuryChangedEvent.OutputObject
    >;
    TreasuryChanged: TypedContractEvent<
      TreasuryChangedEvent.InputTuple,
      TreasuryChangedEvent.OutputTuple,
      TreasuryChangedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
