/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Honk {
  export type RelationParametersStruct = {
    eta: BigNumberish;
    romLogupGamma: BigNumberish;
    beta: BigNumberish;
    gamma: BigNumberish;
    publicInputsDelta: BigNumberish;
  };

  export type RelationParametersStructOutput = [
    eta: bigint,
    romLogupGamma: bigint,
    beta: bigint,
    gamma: bigint,
    publicInputsDelta: bigint
  ] & {
    eta: bigint;
    romLogupGamma: bigint;
    beta: bigint;
    gamma: bigint;
    publicInputsDelta: bigint;
  };
}

export interface RelationsLibInterface extends Interface {
  getFunction(
    nameOrSignature: "accumulateRelationEvaluations"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "accumulateRelationEvaluations",
    values: [
      BigNumberish[],
      Honk.RelationParametersStruct,
      BigNumberish[],
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "accumulateRelationEvaluations",
    data: BytesLike
  ): Result;
}

export interface RelationsLib extends BaseContract {
  connect(runner?: ContractRunner | null): RelationsLib;
  waitForDeployment(): Promise<this>;

  interface: RelationsLibInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accumulateRelationEvaluations: TypedContractMethod<
    [
      purportedEvaluations: BigNumberish[],
      rp: Honk.RelationParametersStruct,
      subrelationChallenges: BigNumberish[],
      powPartialEval: BigNumberish
    ],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accumulateRelationEvaluations"
  ): TypedContractMethod<
    [
      purportedEvaluations: BigNumberish[],
      rp: Honk.RelationParametersStruct,
      subrelationChallenges: BigNumberish[],
      powPartialEval: BigNumberish
    ],
    [bigint],
    "view"
  >;

  filters: {};
}
