/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface BatchVerifierInterface extends Interface {
  getFunction(nameOrSignature: "verifier" | "verifyBatch"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "BatchVerified"): EventFragment;

  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyBatch",
    values: [BytesLike[], BytesLike[][], BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyBatch",
    data: BytesLike
  ): Result;
}

export namespace BatchVerifiedEvent {
  export type InputTuple = [
    subProofs: BigNumberish,
    batchSize: BigNumberish,
    allOk: boolean
  ];
  export type OutputTuple = [
    subProofs: bigint,
    batchSize: bigint,
    allOk: boolean
  ];
  export interface OutputObject {
    subProofs: bigint;
    batchSize: bigint;
    allOk: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BatchVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): BatchVerifier;
  waitForDeployment(): Promise<this>;

  interface: BatchVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  verifier: TypedContractMethod<[], [string], "view">;

  verifyBatch: TypedContractMethod<
    [proofs: BytesLike[], publicInputs: BytesLike[][], batchSize: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyBatch"
  ): TypedContractMethod<
    [proofs: BytesLike[], publicInputs: BytesLike[][], batchSize: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "BatchVerified"
  ): TypedContractEvent<
    BatchVerifiedEvent.InputTuple,
    BatchVerifiedEvent.OutputTuple,
    BatchVerifiedEvent.OutputObject
  >;

  filters: {
    "BatchVerified(uint256,uint256,bool)": TypedContractEvent<
      BatchVerifiedEvent.InputTuple,
      BatchVerifiedEvent.OutputTuple,
      BatchVerifiedEvent.OutputObject
    >;
    BatchVerified: TypedContractEvent<
      BatchVerifiedEvent.InputTuple,
      BatchVerifiedEvent.OutputTuple,
      BatchVerifiedEvent.OutputObject
    >;
  };
}
