/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AgentIdRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "KYC_EXPIRY"
      | "MIN_STAKE"
      | "NAME"
      | "VERSION"
      | "approve"
      | "balanceOf"
      | "burnStake"
      | "complianceSigner"
      | "fleetCount"
      | "fleetQuota"
      | "mint"
      | "name"
      | "ownerOf"
      | "registrar"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setFleetQuota"
      | "stakes"
      | "symbol"
      | "transferFrom"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AgentMinted" | "FleetQuotaSet" | "StakeBurned"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "KYC_EXPIRY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_STAKE", values?: undefined): string;
  encodeFunctionData(functionFragment: "NAME", values?: undefined): string;
  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "burnStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "complianceSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fleetCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fleetQuota",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "registrar", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setFleetQuota",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "KYC_EXPIRY", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_STAKE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "NAME", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burnStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "complianceSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fleetCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fleetQuota", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registrar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFleetQuota",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
}

export namespace AgentMintedEvent {
  export type InputTuple = [
    operator: AddressLike,
    owner: AddressLike,
    agentId: BigNumberish,
    stake: BigNumberish
  ];
  export type OutputTuple = [
    operator: string,
    owner: string,
    agentId: bigint,
    stake: bigint
  ];
  export interface OutputObject {
    operator: string;
    owner: string;
    agentId: bigint;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FleetQuotaSetEvent {
  export type InputTuple = [operator: AddressLike, cap: BigNumberish];
  export type OutputTuple = [operator: string, cap: bigint];
  export interface OutputObject {
    operator: string;
    cap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeBurnedEvent {
  export type InputTuple = [
    to: AddressLike,
    agentId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [to: string, agentId: bigint, amount: bigint];
  export interface OutputObject {
    to: string;
    agentId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentIdRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentIdRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentIdRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  KYC_EXPIRY: TypedContractMethod<[], [bigint], "view">;

  MIN_STAKE: TypedContractMethod<[], [bigint], "view">;

  NAME: TypedContractMethod<[], [string], "view">;

  VERSION: TypedContractMethod<[], [string], "view">;

  approve: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [void],
    "view"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  burnStake: TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;

  complianceSigner: TypedContractMethod<[], [string], "view">;

  fleetCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  fleetQuota: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  mint: TypedContractMethod<
    [
      owner: AddressLike,
      agentId: BigNumberish,
      expiresAt: BigNumberish,
      kycSig: BytesLike
    ],
    [bigint],
    "payable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[agentId: BigNumberish], [string], "view">;

  registrar: TypedContractMethod<[], [string], "view">;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [void],
    "view"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [void],
    "view"
  >;

  setApprovalForAll: TypedContractMethod<
    [arg0: AddressLike, arg1: boolean],
    [void],
    "view"
  >;

  setFleetQuota: TypedContractMethod<
    [operator: AddressLike, cap: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakes: TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, boolean] & { amount: bigint; withdrawn: boolean }],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  transferFrom: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [void],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "KYC_EXPIRY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NAME"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "burnStake"
  ): TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "complianceSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fleetCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "fleetQuota"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [
      owner: AddressLike,
      agentId: BigNumberish,
      expiresAt: BigNumberish,
      kycSig: BytesLike
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[agentId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "registrar"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<[arg0: AddressLike, arg1: boolean], [void], "view">;
  getFunction(
    nameOrSignature: "setFleetQuota"
  ): TypedContractMethod<
    [operator: AddressLike, cap: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, boolean] & { amount: bigint; withdrawn: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [void],
    "view"
  >;

  getEvent(
    key: "AgentMinted"
  ): TypedContractEvent<
    AgentMintedEvent.InputTuple,
    AgentMintedEvent.OutputTuple,
    AgentMintedEvent.OutputObject
  >;
  getEvent(
    key: "FleetQuotaSet"
  ): TypedContractEvent<
    FleetQuotaSetEvent.InputTuple,
    FleetQuotaSetEvent.OutputTuple,
    FleetQuotaSetEvent.OutputObject
  >;
  getEvent(
    key: "StakeBurned"
  ): TypedContractEvent<
    StakeBurnedEvent.InputTuple,
    StakeBurnedEvent.OutputTuple,
    StakeBurnedEvent.OutputObject
  >;

  filters: {
    "AgentMinted(address,address,uint256,uint256)": TypedContractEvent<
      AgentMintedEvent.InputTuple,
      AgentMintedEvent.OutputTuple,
      AgentMintedEvent.OutputObject
    >;
    AgentMinted: TypedContractEvent<
      AgentMintedEvent.InputTuple,
      AgentMintedEvent.OutputTuple,
      AgentMintedEvent.OutputObject
    >;

    "FleetQuotaSet(address,uint256)": TypedContractEvent<
      FleetQuotaSetEvent.InputTuple,
      FleetQuotaSetEvent.OutputTuple,
      FleetQuotaSetEvent.OutputObject
    >;
    FleetQuotaSet: TypedContractEvent<
      FleetQuotaSetEvent.InputTuple,
      FleetQuotaSetEvent.OutputTuple,
      FleetQuotaSetEvent.OutputObject
    >;

    "StakeBurned(address,uint256,uint256)": TypedContractEvent<
      StakeBurnedEvent.InputTuple,
      StakeBurnedEvent.OutputTuple,
      StakeBurnedEvent.OutputObject
    >;
    StakeBurned: TypedContractEvent<
      StakeBurnedEvent.InputTuple,
      StakeBurnedEvent.OutputTuple,
      StakeBurnedEvent.OutputObject
    >;
  };
}
