/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface BehaviorProofInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchorReceipts"
      | "disputeCount"
      | "disputes"
      | "openDispute"
      | "receipts"
      | "resolveDispute"
      | "slash"
      | "slashed"
      | "slasher"
      | "totalSlashed"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeOpened"
      | "DisputeResolved"
      | "ReceiptsAnchored"
      | "Slashed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "anchorReceipts",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "openDispute",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receipts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "slash", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "slashed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "slasher", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSlashed",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "anchorReceipts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disputes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "openDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "receipts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "slash", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "slashed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "slasher", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSlashed",
    data: BytesLike
  ): Result;
}

export namespace DisputeOpenedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    disputeId: BigNumberish,
    challenger: AddressLike,
    evidenceRoot: BytesLike
  ];
  export type OutputTuple = [
    agentId: bigint,
    disputeId: bigint,
    challenger: string,
    evidenceRoot: string
  ];
  export interface OutputObject {
    agentId: bigint;
    disputeId: bigint;
    challenger: string;
    evidenceRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    disputeId: BigNumberish,
    upheld: boolean
  ];
  export type OutputTuple = [
    agentId: bigint,
    disputeId: bigint,
    upheld: boolean
  ];
  export interface OutputObject {
    agentId: bigint;
    disputeId: bigint;
    upheld: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiptsAnchoredEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    root: BytesLike,
    anchoredAt: BigNumberish
  ];
  export type OutputTuple = [agentId: bigint, root: string, anchoredAt: bigint];
  export interface OutputObject {
    agentId: bigint;
    root: string;
    anchoredAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SlashedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    by: AddressLike,
    slashedAt: BigNumberish
  ];
  export type OutputTuple = [agentId: bigint, by: string, slashedAt: bigint];
  export interface OutputObject {
    agentId: bigint;
    by: string;
    slashedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BehaviorProof extends BaseContract {
  connect(runner?: ContractRunner | null): BehaviorProof;
  waitForDeployment(): Promise<this>;

  interface: BehaviorProofInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchorReceipts: TypedContractMethod<
    [agentId: BigNumberish, root: BytesLike],
    [void],
    "nonpayable"
  >;

  disputeCount: TypedContractMethod<[agentId: BigNumberish], [bigint], "view">;

  disputes: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, bigint, boolean, boolean] & {
        challenger: string;
        evidenceRoot: string;
        openedAt: bigint;
        resolved: boolean;
        upheld: boolean;
      }
    ],
    "view"
  >;

  openDispute: TypedContractMethod<
    [agentId: BigNumberish, evidenceRoot: BytesLike],
    [bigint],
    "nonpayable"
  >;

  receipts: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { root: string; anchoredAt: bigint }],
    "view"
  >;

  resolveDispute: TypedContractMethod<
    [agentId: BigNumberish, disputeId: BigNumberish, upheld: boolean],
    [void],
    "nonpayable"
  >;

  slash: TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;

  slashed: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  slasher: TypedContractMethod<[], [string], "view">;

  totalSlashed: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchorReceipts"
  ): TypedContractMethod<
    [agentId: BigNumberish, root: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputeCount"
  ): TypedContractMethod<[agentId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "disputes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, bigint, boolean, boolean] & {
        challenger: string;
        evidenceRoot: string;
        openedAt: bigint;
        resolved: boolean;
        upheld: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "openDispute"
  ): TypedContractMethod<
    [agentId: BigNumberish, evidenceRoot: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "receipts"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { root: string; anchoredAt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [agentId: BigNumberish, disputeId: BigNumberish, upheld: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "slash"
  ): TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "slashed"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "slasher"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalSlashed"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "DisputeOpened"
  ): TypedContractEvent<
    DisputeOpenedEvent.InputTuple,
    DisputeOpenedEvent.OutputTuple,
    DisputeOpenedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "ReceiptsAnchored"
  ): TypedContractEvent<
    ReceiptsAnchoredEvent.InputTuple,
    ReceiptsAnchoredEvent.OutputTuple,
    ReceiptsAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "Slashed"
  ): TypedContractEvent<
    SlashedEvent.InputTuple,
    SlashedEvent.OutputTuple,
    SlashedEvent.OutputObject
  >;

  filters: {
    "DisputeOpened(uint256,uint256,address,bytes32)": TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;
    DisputeOpened: TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;

    "DisputeResolved(uint256,uint256,bool)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "ReceiptsAnchored(uint256,bytes32,uint64)": TypedContractEvent<
      ReceiptsAnchoredEvent.InputTuple,
      ReceiptsAnchoredEvent.OutputTuple,
      ReceiptsAnchoredEvent.OutputObject
    >;
    ReceiptsAnchored: TypedContractEvent<
      ReceiptsAnchoredEvent.InputTuple,
      ReceiptsAnchoredEvent.OutputTuple,
      ReceiptsAnchoredEvent.OutputObject
    >;

    "Slashed(uint256,address,uint64)": TypedContractEvent<
      SlashedEvent.InputTuple,
      SlashedEvent.OutputTuple,
      SlashedEvent.OutputObject
    >;
    Slashed: TypedContractEvent<
      SlashedEvent.InputTuple,
      SlashedEvent.OutputTuple,
      SlashedEvent.OutputObject
    >;
  };
}
