/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AgentAccountMinimal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AgentAccountMinimal__factory>;
    getContractFactory(
      name: "AgentIdRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AgentIdRegistry__factory>;
    getContractFactory(
      name: "BehaviorProof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BehaviorProof__factory>;
    getContractFactory(
      name: "CertIssuer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CertIssuer__factory>;

    getContractAt(
      name: "AgentAccountMinimal",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AgentAccountMinimal>;
    getContractAt(
      name: "AgentIdRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AgentIdRegistry>;
    getContractAt(
      name: "BehaviorProof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BehaviorProof>;
    getContractAt(
      name: "CertIssuer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CertIssuer>;

    deployContract(
      name: "AgentAccountMinimal",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentAccountMinimal>;
    deployContract(
      name: "AgentIdRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentIdRegistry>;
    deployContract(
      name: "BehaviorProof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BehaviorProof>;
    deployContract(
      name: "CertIssuer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CertIssuer>;

    deployContract(
      name: "AgentAccountMinimal",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentAccountMinimal>;
    deployContract(
      name: "AgentIdRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentIdRegistry>;
    deployContract(
      name: "BehaviorProof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BehaviorProof>;
    deployContract(
      name: "CertIssuer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CertIssuer>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
